### ISSUE TITLE
Version 0.5.11 issue in 64 bits

### ISSUE THREAD

**Issue by LUiZiNH0** [opf/OpenProjectExcel#10]
Hi, in MS Office 64 bits, when opening the version 0.5.11. An error occurs stating that this code must be updated for use on a 64bit system. The compilation error occurs on these line, in BasicModul: "Declare Function GetSystemMetrics Lib "user32" (ByVal nIndex As Long) As Long"

If comment these lines in BasicModul The build is successful:
'Declare Function GetSystemMetrics Lib "user32" (ByVal nIndex As Long) As Long
'Breite = GetSystemMetrics(1)
'Hoehe = GetSystemMetrics(0)

**Comment by bpetraus** [comment]
Hi @LUiZiNH0 , thank you for reporting! I had to remove the responsive fomular stuff at all. So formularsize is hardcoded for now.
