### ISSUE TITLE
Closed work packages are not downloaded

### ISSUE THREAD

**Issue by sunishnet** [opf/OpenProjectExcel#11]
I was trying to download workpackages from one instance of OP to upload to another, kind of migration. But I find closed workpackages are not downloaded. Any solution/work around ?

**Comment by bpetraus** [comment]
Hi @sunishnet ,

Thats its how its meant to be. You get the standard view. So what you see in OpenProject is the same as in Excel. And in standard view, there are no closed workpackages.

But you brought up a good point. You have to create a custom filter without any filter. Then you'll need to get the query id to download all related workpackages. You can find the query id in the URL, once you have successfully selected a filter:

"https://......../work_packages?query_id=**6671**"

Put it in the Excel form and thats it.

Best

Bernd

**Comment by sunishnet** [comment]
Hi Bernd,
Wow, that was fast. Your solution worked as expected. I created a filter with all workpackages and then made it public/favoured. Got the query id and could download all WPs.

Thanks,
Sunish
