### ISSUE TITLE
Downlaod of relations

### ISSUE THREAD

**Issue by lindenthal** [opf/OpenProjectExcel#12]
Hi @bpetraus,

We have a client that has n:m-entities in OpenProject.

Product:Contract:Customer

Now they asked me for an easy way to have reports on these the transitive relationship between Products and Customers: "What Customer uses one specific Product".

Currently this filter not possible in OpenProject so I am wondering if they could use your Excel macro to generate these reports.

So my question is: Currently your macro does not sync relations others than parents, right? I couldn't find a column "related to" so I assumes additional work is required, right?

Best
Niels

**Comment by bpetraus** [comment]
Hi @lindenthal 

the API provides the required information. 

I dont make any use of it, because there was no proper way to present theese information. 

But, it should be easy to show the ids of related workpackages in a additional column, but thats not enough, I guess.

Best

Bernd

**Comment by lindenthal** [comment]
Hi @bpetraus,

yes, you are right. It is difficult to make use of it. 

I guess they have to use this to get the "raw data" for customers, contracts and products. And then they need to do some magic in Excel (e.g SVERWEIS).

Best
Niels

**Comment by bpetraus** [comment]
Hi @lindenthal 

think so. With the ids of related workpackages and some advanced excel skills, it wouldnt be a big deal to get the required informations.

Please let me know, if they would make any use of a additional column "relations".

Best

Bernd

**Comment by bpetraus** [comment]
Theres a new function addressing this and additional stuff. You can now download the ids of related workpackages and create a report to analyse all of theese relations.
