### ISSUE TITLE
Automatic Update of Non Selected Custom Field

### ISSUE THREAD

**Issue by FloStoyadin** [opf/OpenProjectExcel#13]
Hi @bpetraus ,

a custom field (format -> list, most recent one added to our system) keeps getting updated (it seems to not change anything though) while updating fields in existing work packages, even though that particular field is NOT selected in the template.

The update does not happen in every work package selected in the template though.

Unfortunately "reinstallation" of the template did not solve the problem.

It may be a long shot, but do you have any idea what might cause that to happen?

Thanks in advance,
Flo

**Comment by bpetraus** [comment]
Hi @FloStoyadin 

I'm sorry, I'm not sure, if I understand you correctly.

Let me try to formulate the problem by myself: 

- There is a workpachage with several attributes and a custom attribute (formatted as list). The custom attribute has value, lets say "A".
- After downloading this workpackage to the Excel sheet and upload it right again, without any changes, the workpackage gets updated and activity shows that custom attribute has set from "A" to "A".

Additionaly:

- All of this happens even the column of the custom field is not selected in the Excel sheet.
- It happens not necessary to every workpackage dowloaded to Excel sheet.

Did I got you right?

Best

Bernd

**Comment by FloStoyadin** [comment]
Thanks for the quick reply!

And yes.... exactly as you described it.

Best Regards
Flo

**Comment by bpetraus** [comment]
Ok, so what next would be interested to know is, why it doesnt update every workpackage downloaded to the Excel sheet. Can you please try to figure out, if there're some commonalities of the updated workpackages, e.g. umlauts or something?

**Comment by FloStoyadin** [comment]
"Umlauts" in the title of the work package are pretty rare, what a lot of them contain are points and hyphens (in general). The custom field title itself does not contain any of those, but some of its values contain "Umlauts". 

The vast majority of the work packages hold a lot values for that custom field (20/30+), but there are some work packages containing less than 10 or even a single value and those still get updated.

I hope that helps you out a bit.

**Comment by bpetraus** [comment]
Hi @FloStoyadin 

I did some testing. But I wasnt able to reproduce your problem. Is there any way to send me a example excel? Do you have a test instance of OpenProject?

Best

Bernd

**Comment by FloStoyadin** [comment]
Sorry it took me a while, shared a repo with you.

Best Regards
Flo

**Comment by bpetraus** [comment]
Problem is not related to the excelsheet in first place.
