### ISSUE TITLE
Order by hierarchy

### ISSUE THREAD

**Issue by olivierdalang** [opf/OpenProjectExcel#14]
Hi !

It doesn't seem possible currently to have the rows ordered by hierarchy in Excel.

That would be a nice feature, especially if displayed with the 4 spaces indent trick, as it would start to look very similar to what you see in open-project.

Maybe attributes such as "order" and "hierarchical order" could be retrieved, to allow this ? (not sure how it works internally)

Cheers

**Comment by bpetraus** [comment]
Hi @olivierdalang 

thank you. Can you please try the new function?

Maybe I'll add some aggregation function or something in future. Shouldnt be a big deal.

Best

Bernd

**Comment by olivierdalang** [comment]
@bpetraus Wow, that was fast. Just tested, and it seems to work well ! Thanks so much !!!

**Comment by bpetraus** [comment]
Your welcome. You were lucky, I didnt had much to do on new years day. :)
