### ISSUE TITLE
After failed import the workpackage status list is broken

### ISSUE THREAD

**Issue by cybernoid** [opf/OpenProjectExcel#18]
I connected the server and it downloaded the attributes as expected. The usual workpackage status fields (default from OpenProject installation: "New", "In specification", "Specified", "Confirmed", "To be scheduled", ....) did not show up, instead the drop down contained "New", "In progress", "Closed", "on hold" and "Rejected". After uploading the changes, the list of workpackage stati in OpenProject also has been replaced! The original items can still be seen in the administrators configuration, but the are no longer available in any project.

What's going wrong here and how can I repair my OpenProject installation?

Thanks in advance!

**Comment by cybernoid** [comment]
Ok I just understood somewhat more about OpenProject. Obviously there are two different lists of possible workpackage stati, one for Tasks, Phases and so on and the other for Features, Bugs and User Stories. The Excel sheet obviously allows only values from the first list, no matter what the workpackage type is.

The question remains however why none of my newly created workpackages in the Excel sheet shows up in OpenProject after synchronization, whereas modifications of existing workpackages are synchronized without problems.

**Comment by bpetraus** [comment]
Hi @cybernoid , did you receice any message in the column "updatestatus" for the affected workpackages?

**Comment by cybernoid** [comment]
For the modified workpackages it contains "200 - OK", but for the newly created workpackages the column remains empty.

**Comment by bpetraus** [comment]
That indicates it stops right before the workpackages. 

Is there a empty row before? It shoudn't, because thats the marker for stopping.

Can you try to delete all the other rows before? Just for testing.

**Comment by bpetraus** [comment]
Re. statuses: Status is a special case in OpenProject. 

It depends on workflows the admin defines. (see admin config) When you try to change a status in OpenProject a list of "allowed" status values is shown. What is allowed depends on the value it has been before, whats the users role and what workpackage type. 

In the Excel this usability feature is not provided. So in the dropdown in Excel you may see other values than in OpenProject. Although, you get a error message in the column "updatestatus" if you try something, that is not allowed.

**Comment by cybernoid** [comment]
The problem with inserting new entries was that I tried to provide an ID, which seems not to be allowed. Everything seems to work now, thank you very much for your support!

**Comment by bpetraus** [comment]
Thats indeed not allowed. You can not define ids by yourself, neither in Excel nor in OpenProject. Just for clarification. Once an id is provided, it is assumed the workpackages already exists. If no id is peovided its about to create a new one.
