### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by dot452** [opf/OpenProjectExcel#21]
So excited to use this, but I'm running into this error when hitting "Accept". I'm using Office 365, but I'm trying to find out how to download older versions of Excel to try to troubleshoot. Thought I'd post this issue here in the meantime.

Err.Raise 10001, "JSONConverter", json_ParseErrorMessage(JsonString, json_Index, "Expecting '{' or '['")

**Comment by bpetraus** [comment]
hi @dot452 can you please eplain your case in more detail? What did you tried? Where did it stopped exactly?

**Comment by dot452** [comment]
Hi @bpetraus , sure thing-
- I followed the instructions on this page: https://www.openproject.org/synchronize-excel-openproject/
- I was using Office 365 because that's what my work uses
- The file would either not open and I'd get a "file corrupt, could not open" error, or, I would be able to open it, and I'd be able to fill out the information, but then I'd get the error described in my first comment.

I was able to get it to work after downloading Excel 2016 on my home PC.

**Comment by bpetraus** [comment]
Hi @dot452 vba doesnt work in the web apps for obvious reasons. I was considering switching to excel web app addin, but this would be a big deal. So I postponed it for now. Sorry.
