### ISSUE TITLE
Missing fields and data

### ISSUE THREAD

**Issue by 4integration** [opf/OpenProjectExcel#24]
Hi,

Trying out OpenProject and have registered a few tasks and some relations as can be seen on screenshot below:

![image](https://user-images.githubusercontent.com/11057350/93604327-85fc4f00-f9c5-11ea-9e4e-5e22085707b8.png)

When using this Excel tool I only get 4 columns and data for them.

![image](https://user-images.githubusercontent.com/11057350/93604262-6e24cb00-f9c5-11ea-94ff-d59177cfb6cf.png)

Using Excel 16.0.10363.20015 and OpenProject 10 in docker (openproject/community:10)

**Comment by bpetraus** [comment]
Hi @4integration ,

unfortunately it is not possible to predefine the columns.

But its very easy to add the columns by yourself, like you can see for example in this video: (at 4:30)

https://www.youtube.com/watch?v=ZPK-l-e-lKI

Best

Bernd
