### ISSUE TITLE
New "instance" field in excel Sync set-up windows

### ISSUE THREAD

**Issue by pdl86** [opf/OpenProjectExcel#26]
Hello 

in the latest OpenProject Excel sync tool, a new field "Instance" appears in the upload/download set-up pop up : 

![image](https://user-images.githubusercontent.com/30148795/100910861-c6e90780-34ce-11eb-80ed-970c44ffcffb.png)

Any hint waht to put in as it looks like that everything but http:// is rejected , adn then I get an error invalid http command.

thanks for help.
regards
Phil

**Comment by bpetraus** [comment]
hi @pdl86 ,

actually the line above is the new one. There you can copy paste an complete Openproject URL and the rest is autofilled, e.g.:

Paste "https://community.openproject.com/projects/excel-sync/work_packages?query_id=2550" in line 1 and you will get this automatically:

Instance URL: https://community.openproject.com/
Project: excel-sync
QueryID: (opt.) 2550

Sorry for the confusion, but does it work now with this new understanding?

Bernd

**Comment by pdl86** [comment]
Hi Bernd,

Thanks for you review. But unfortunaltely it does not seems to work : 

I did  what you recommended : 
paste the URL in line 1 , leaving the second empty 

Once cliking on Accept, I get an error : URL empty.

If I try to type the instance URL ; it is limited to "https:/"

![image](https://user-images.githubusercontent.com/30148795/101153507-d5e1ce00-3624-11eb-9a1a-ec1f1e3a0cac.png)

Note that if yout URL contains extra characters after the query_id=xx , the you get an error

Thanks for your help

Best regards

Philippe

**Comment by pdl86** [comment]
Hi Berned

If I paste the URL and "kick" entre, then the second field fille dwith "only" http:/" and then the Macro claims that the URL is invalid;

![image](https://user-images.githubusercontent.com/30148795/101153860-3e30af80-3625-11eb-9e51-3a43dfa1b8e5.png)

**Comment by bpetraus** [comment]
Hi @pdl86 ,

oh, you're running it local. Never tested before.

Please try the following:

URL: (Autofill) keept it empty
Instance URL: http://localhost:8080/
Project: revival-2023

Best

Bernd

**Comment by pdl86** [comment]
Hi Bernd

If I try to copy http://localhost:8080:/ in the second field , I get "only" http:/
![image](https://user-images.githubusercontent.com/30148795/101154343-e9416900-3625-11eb-99ac-32b5cf59850c.png)

**Comment by bpetraus** [comment]
Hi @pdl86 ,

I just uploaded a fresh version, where you can fill in localhost URLs and it will not not messed up. 

Can you give it a try?

Best

Bernd

**Comment by bpetraus** [comment]
U can use the Autofill as well as the Instance URL, if you want.

**Comment by pdl86** [comment]
Hi Bernd

Now i works like a charm ( bot the Autofil and Instance) .
many thanks.

Still the issue #29 see comments there.

You can close

regards
philippe
