### ISSUE TITLE
VBA errors when loading the default parameters

### ISSUE THREAD

**Issue by sangorys** [opf/OpenProjectExcel#30]
I have VBA error messages when loading the default parameters.

Reason : to change a text box, we need to define **.Text**. Eg. .URLTextBox becomes .URLTextBox.Text

Please replace the functions by this one :

Sub Standard()

With ChooseProjectForm

    .URLTextBox.Text = DefaultSheet.Range("URLStandard")
    .ProxyCheckBox = DefaultSheet.Range("ProxyStandard")
    .APIKeyTextBox.Text = DefaultSheet.Range("APIKeyStandard")
    .ProjectTextBox.Text = DefaultSheet.Range("ProjectStandard")
    .QueryIDTextBox = DefaultSheet.Range("QueryIDStandard")
    .HierarchyCharactersTextBox = DefaultSheet.Range("HierarchyMarkerStandard")

End With

**Comment by bpetraus** [comment]
Hi @sangorys ,

thank you! That was a little clumsy and is for sure much better now. :)

But I'm still wondering, why this leads to an error. May I ask, what excel version do u have?

Best

Bernd

**Comment by sangorys** [comment]
![image](https://user-images.githubusercontent.com/544194/101612149-9f33fb00-3a0a-11eb-92ab-2a054979ac23.png)

**Comment by bpetraus** [comment]
@sangorys , same like me. Any ideas, why it wasnt working at your machine?
