### ISSUE TITLE
Improvement request : automatically upload the default configuration

### ISSUE THREAD

**Issue by sangorys** [opf/OpenProjectExcel#31]
Hello,

**SUGGESTION :**
instead of having the **Load default** button in **ChooseProjectForm**, I suggest to automatically load the default configuration.

**HOW :**
1. Just add before **Formular.Show** in **BasicsModul.FormularSize()** :

`Call MainModul.Standard`

2. Then you can clean the file :
- delete the **Load default** button 
- delete sub **StandardCommandButton_Click**()

Not a huge improvement but it is anoying to always click on it each time we open the **ChooseProjectForm**

**Comment by bpetraus** [comment]
hi @sangorys ,

I just added the auto-load, when open the form. Great suggestion.

But I kept the buttons. :)

Best

Bernd

**Comment by sangorys** [comment]
Great : thanks
