### ISSUE TITLE
Improvement request : have a trace of the sent HTTP requests

### ISSUE THREAD

**Issue by sangorys** [opf/OpenProjectExcel#32]
[OpenProjectAPI.zip](https://github.com/opf/OpenProjectExcel/files/5689195/OpenProjectAPI.zip)

### INTRO :

Hello again  :)

I am working on the communication between OpenProject and Excel and this project helps me a lot (**thanks** again, by the way).

Something I need is to understand which HTTP requests and responses are sent / received.

### IDEA
For that, I had this idea :
- Add a sheet to see all HTTP requests
(in order to avoid a huge file, the sheet is reseted each time we click on a button)

### IMPLEMENTATION
If you are interested in this idea, I developped it . This is very simple with 3 simple steps :
- A **new sheet** called "**HTTP frames**" which shows all HTTP requests and responses
- A **new module** called **FrameModule** with the function **writeFrameToFrameSheet** which writes the HTTP frames
- The function is called twice in function **OpenProjectAPIModul.OpenProjectAPI()** 
  - after the line : _OpenProjectAPI.Add "Status", .Status_
    - we can insert : _Call writeFrameToFrameSheet(MethodStr, URLCompleteStr, BodyStr, objHTTP)_
  - before the line _If BodyStr = Empty Then_ : 
     - we can insert : _Call writeFrameToFrameSheet(MethodStr, URLCompleteStr, BodyStr, objHTTP)_
](url)

If you think that this idea is good but universally, we can imagine having an option to enable / disable it.

Please contact me if you need anything on this topic :)

**Comment by bpetraus** [comment]
hi @sangorys 

i liked the idea and so I implemented it. (due to extended lunch time :))

But, it can become plenty of data and didnt want to have it in the Excle file. Plus, excel cells are limited to 32k characters.

So I decided to export a file (to downloads folder of user). The file is updated, not replaced. So delete it from time to time.

Hope that helps.

Best

Bernd
