### ISSUE TITLE
Update Relations

### ISSUE THREAD

**Issue by bpetraus** [opf/OpenProjectExcel#37]

**Comment by bpetraus** [comment]
Reminder

**Comment by larimow** [comment]
Hi Bernd,
what is the status on the relations update? We are about to import a project plan with 1000+ entries into OpenProject and updating relations manually is a real pain in the a...
As it is possible to download work packages including their relations it should be possible to update them as well via the API, right? What are the main issues here?

**Comment by bpetraus** [comment]
Hi @larimow ,

it's in general a matter of time. This Excel is more a weekend project, you know? 

But it should not be a big deal, since all we need is provided via API, as far as i can see.

The only thing can imagine, would be the specification of a relation. right now it's like "follows: 12345". that could be a little bit fragile.

Let me take a look on it, this weekend.

Best

Bernd

**Comment by larimow** [comment]
Great, thank you. Honestly, I'm the development lead of one of your Enterprise Clients so I can ask for official support and you might be able to work on this project during, well working hours.

**Comment by lindenthal** [comment]
Hi @larimow,

Niels here - CEO of OpenProject. 
Just to make sure we are on the same page here:

We do not support this Excel-Sheet. This is a community-driven project. If you got information stating something different please let me know.

Best
Niels

**Comment by larimow** [comment]
Hi Niels,
in that case I apologise and retract my comment. I can delete it alltogether if this is preferred.

Best Regards
Larimow

**Comment by bpetraus** [comment]
Hi @larimow ,

you can handle this however you want, I dont think this is neccessary though. It was a well-meant offer from your side. And Niels just states the fact that the excel file is a community project and OpenProejct doesnt provide official support.

Let me check, what I can achieve at the weekend. :)

Best

Bernd

**Comment by larimow** [comment]
Hi @bpetraus,

thank you for you efforts! I have to admit though, that I was not able to make it run. I created a test project, manually set relations in the OpenProject GUI and tried to download it. "*Relations" stayed empty, the rest worked fine. I would have liked to test it the other way round, so setting relations in the Excel sheet and uploading them but I forgot the syntax and couldn't find it anywhere. 
Might you tell me, what the actual syntax for relations is so that I can test that use case? 

Regards
Larimow

**Comment by larimow** [comment]
Hi Bernd,
I tried this out today and I can download relations again from the model. 
On creating new relations the following happened:

- Created a new task
- Added a follows relation
- Got a "Laufzeitfehler '13': Typen unverträglich
- Opened and closed debugging (did not find anything there on first glance)
- Task has not been created

Next, I tried another route:

- created another task
- updated WPs
--> Task successfully created
- added a follows relation
- updated WPs
--> Relation has been created (added a rel. ID in *Relations)
--> Received the following message in Updatestatus: 409 - Die Ressource konnte wegen parallelen Zugriffs nicht aktualisiert werden. (Details: {"_type":"Error","errorIdentifier":"urn:openproject-org:api:v3:errors:UpdateConflict","message":"Die Ressource konnte wegen parallelen Zugriffs nicht aktualisiert werden."})
- Updated WPs again
--> Received a "200 - OK" Status
--> Task has succesfully been updated, verified in the UI

I would say good work so far! It's still a little tricky and the cause for the 409 should still be identified but it's at least working for now. By the way, are you coding with [Rubberduck](https://rubberduckvba.com/) or are you using the horrible UI from Excel? I know it's only a side project but in case someone in the community or some colleagues might come to your aid, unit testing and all the other nice features from Rubberduck might really elevate the project. Well, unless you are already using it already anyway. 

Thank your for your efforts!

Cheers
Sebastian

**Comment by larimow** [comment]
Hi @bpetraus,
I just tested the new version. Creating a new version while at the same time adding relations works properly now, thank you for your efforts!
There is one caveat that I would address in the documentation: to fully use this feature you have to:

- Open the Excel sheet
- Configure the project
- Add the column Relations to your table
- Save and close the Excel sheet
- Open the Excel sheet again
- Download the work packages of the project if there are any
- Now it's fully functional

Without restarting the application no relations will be downloaded during an update/download process. The creation of new work packages and relations works, though. It's not a big thing, I guess it will simply help to have it in the documentation. 

Regards
Sebastian
