### ISSUE TITLE
I needed some fixes to compile it.

### ISSUE THREAD

**Issue by unaginokabayaki** [opf/OpenProjectExcel#4]
I needed some fixes to compile it.
* Progressbar control is not available for 64bit excel
* typo at .Sort.SortFields.Add
* missing double quote around TextStr = Replace(TextStr, "\u00E0", "・", , , vbBinaryCompare)

**Comment by bpetraus** [comment]
Hi, 

unfortunately I have no 64 bit version. So I can not reproduce your issues. What I have done:

* I replaced the progressbar by another, wich should also work for 64 bit Excel.
* I fixed the "typo". (see also [#29628](https://community.openproject.com/projects/excel-sync/work_packages/details/29628/overview)
* I'm not able to see your point. Can you provide som details? Wich language do you use?

Please leave a feedback.

Regards

Bernd
