### ISSUE TITLE
Deactivate certificat check

### ISSUE THREAD

**Issue by larimow** [opf/OpenProjectExcel#40]
Hi guys,
thank you for this Excel Sheet, it did really help me in the past. However, we're currently operating Open Project with self-signed certificates in a closed off environment and I'm hence getting an abort due to a certificate error. Is there a way to deactivate the certificate check or to manually accept the self-signed one?
Regards
Larimow

**Comment by larimow** [comment]
We'll try to solve the problem otherwise

**Comment by bpetraus** [comment]
@larimow thanks for the closing the ticket and note.
