### ISSUE TITLE
Visual Basic Compile Error: Syntax Error

### ISSUE THREAD

**Issue by kimannakim** [opf/OpenProjectExcel#42]
Hi, I am trying to do Excel synchronization with Open Project. 

However, after clicking on Accept button, I receive this error
`Microsoft Visual Basic for Applications Compile Error: Syntax error` alert

The Visual Basic Debugger opens up, and the following line is highlighted:
`Function ConvertFromUnicodeJava(TextStr As String) As String`

I've never use VBA before, hence need help on how to handle this. Thank you!

**Comment by Nimbulaxan** [comment]
There is nothing wrong with what you have provided, the issue must be somewhere in the code of the function or in how you are calling the function. My best guess without seeing the rest of the code is that either what you are passing in is not of type String or what you are returning is not of type String.

**Comment by kimannakim** [comment]
Yes, you're right. I'm missing " from the string. Thank you!
