### ISSUE TITLE
Script-Prefix of OpenProject instance is ignored

### ISSUE THREAD

**Issue by srkunze** [opf/OpenProjectExcel#43]
Using the `URL: (autofill)` field does not respect a given script prefix of the web instance, e.g.:

![image](https://user-images.githubusercontent.com/1389648/139888939-49bcb30d-26d5-4b20-8fbb-b9bc6bed44ac.png)

**Comment by bpetraus** [comment]
Hi @srkunze 

oh, I wasnt aware of this. Can you try to give an example of the complete URL? (without red) You can give a finctional example. Its just about the syntax.

Best

Bernd

**Comment by bpetraus** [comment]
@srkunze Does it work, if you fill it out like this?

![image](https://user-images.githubusercontent.com/38315559/140176915-becfa98c-690e-4b1d-a24e-ac2f7c265630.png)

**Comment by srkunze** [comment]
I thought it was obvious but yes, you are right. The expected `instance url` and `project` should look like in your screenshot after pasting in the `URL: (Autofill)` field. This would be awesome! :-)

**Comment by bpetraus** [comment]
@srkunze :D It is obvious, but not what I meant. 

What I mean, dos import/ export of workpackages work properly, when you fill it out like this?

**Comment by srkunze** [comment]
OK, I see. That implies two things:

1) Yes, filling out the form in this way works; it is automatically filled this way when re-opening the Excel sheet 👍

2) I would never ever expect it to work differently when I use either "URL: (Autofill)" or "instance url"+"project" or when I use both in combination. I am curious of why should it behave differently? I for one would be extremely confused. 😀

**Comment by bpetraus** [comment]
re. 2: I was just trying to find out, if theres any problem other than properly splitting "URL: (Autofill)" into "Instance URL:", "Project" and "QueryID: (opt.)", because I'm not able to test this case. by the way, does it work now?

**Comment by srkunze** [comment]
@bpetraus You don't need an corresponding OpenProject instance. It's just the splitting. :-)

I downloaded the current Excel-file via the zip functionality of Github but it doesn't show the expected functionality. I didn't find a testsuite for this project but I added some testcases below which I would see to be relevant for this issue :-)



Here is a list of inputs for "URL: (Autofill)" and their expected outputs for "Instance URL:" + "Project"



`https://example.org/openproject/projects/myproject/` => `https://example.org/openproject/` + `myproject`
`https://example.org/openproject/projects/` => `https://example.org/openproject/` + ` `
`https://example.org/openproject/` => `https://example.org/openproject/` + ` `

`https://example.org/projects/myproject/` => `https://example.org/` + `myproject`
`https://example.org/projects/` => `https://example.org/` + ` `
`https://example.org/` => `https://example.org/` + ` `

**Comment by bpetraus** [comment]
@srkunze Thank you for the examples. That was quite helpful. Can u pls test it?

Best

Bernd

**Comment by srkunze** [comment]
Hi Bernd,

yes. It works now. :-) 

Thanks a lot.
Sven
