### ISSUE TITLE
Type Mismatch When Initializing Projects

### ISSUE THREAD

**Issue by dcbell** [opf/OpenProjectExcel#5]
When first using the file, after setting up the URL, API Key, and identifier, then clicking accpet:

![choose project](https://user-images.githubusercontent.com/930515/58439729-52dcd080-809b-11e9-94a0-588339b46849.png)

I get a `Run-time error ' 13': Type mismatch.`. 

![after accept - error](https://user-images.githubusercontent.com/930515/58439736-6425dd00-809b-11e9-9bcd-6dd036b9c69f.png)

I went into the VBA debugger, and the error is on this section of code:

```
With ProjectsSheet

    'ProjectIDLng = .Range("ID").Value2(.Row - .Range("ID").Row + 1, 1)
      
    Set SearchResultRng = .Range("Identifier").Find(ProjectStr, LookIn:=xlValues, LookAt:=xlWhole)
    If Not SearchResultRng Is Nothing Then ProjectIDLng = .Range("ID").Value2(SearchResultRng.Row - .Range("ID").Row + 1, 1)

End With
```

I unhid the Projects tab and then changed the IF Not line to read `If Not SearchResultRng Is Nothing Then ProjectIDLng = 3` where 3 was the ID of the project listed on the Projects tab. After that, it would upload/download work tasks just fine. So the full working section was:

```
With ProjectsSheet

    'ProjectIDLng = .Range("ID").Value2(.Row - .Range("ID").Row + 1, 1)
      
    Set SearchResultRng = .Range("Identifier").Find(ProjectStr, LookIn:=xlValues, LookAt:=xlWhole)
    If Not SearchResultRng Is Nothing Then ProjectIDLng = 3

End With
```

Obviously that won't work as a general purpose fix, just a one time deal to get some things loaded.

**Comment by bpetraus** [comment]
Hi dcbell,

thank you for detailed report!

I wasnt able to confirm your bug, although I did a adjustment in the mentioned line of code. But that shouldn't explain the bug. You can give it a try, anyway.

Here're some additional thoughts on that. As you surely figured out, theres a worksheet called "Projects". Here happens the mapping from identifier to projectid as you did manually by setting to "3".

SearchResultRng (one line above) is the cell found by identifier. (usually in the first column in sheet "Projects")  It would be interesting, what is found, when code stops at the next line. Simply hover the mouse cursor over SearchResultRng after debugger stops code and please report what is shown.

Best regards

Bernd
