### ISSUE TITLE
OP 14X Error parsing JSON:

### ISSUE THREAD

**Issue by bselcuk** [opf/OpenProjectExcel#66]
Hi. Before OpenProject 14x, I was able to use Excel synchronization. However, after entering URL, token, and other information on the settings page, I'm encountering errors when trying to check the project. Is the Excel synchronization not compatible with version 14x? Has anyone else experienced this issue? @bpetraus 
![image](https://github.com/opf/OpenProjectExcel/assets/15174734/3c9cab37-76bf-45c4-89e8-e756be680215)
![image](https://github.com/opf/OpenProjectExcel/assets/15174734/79c0f2a8-4d63-425c-941a-5531d73be648)

[14x change log  ](https://www.openproject.org/docs/release-notes/14-0-0/)

![image](https://github.com/opf/OpenProjectExcel/assets/15174734/e0a6715b-58fd-4f65-884a-ed46e6de4304)

in Excel 

![image](https://github.com/opf/OpenProjectExcel/assets/15174734/e4de5d78-d6a5-4d42-90d7-340ae9374af9)

**Comment by bselcuk** [comment]
![image](https://github.com/opf/OpenProjectExcel/assets/15174734/92ad7850-8e2f-44a6-ab1b-f5c8ac3b03ef)

in Excel --> OpenProjectAPIModul --> GetAttributes

remove           **Or .Cells(i, 1).Value = "responsible"** 

![image](https://github.com/opf/OpenProjectExcel/assets/15174734/9c493843-9014-40d7-873d-ab7e50b9401d)


end so start working 💯

**Comment by bpetraus** [comment]
Hi @bselcuk ,

I've just updatet the Excel file. It should work now.

See also: #65 

Best
