### ISSUE TITLE
Estimated Time and Remaining hours

### ISSUE THREAD

**Issue by DanyHubGit** [opf/OpenProjectExcel#7]
It's not possible to decode the format of these two fields (Estimated Time and Remaining hours).
If I put a value of **Estimated Time=1000 hours**, in excel the value read is **P41DT16H**

Do you know how we can decode this value?

Thanks in advance

The same behaviour is for the field Remaining Hours

**Comment by ulferts** [comment]
Both attributes are in the [ISO 8601 duration format](https://en.wikipedia.org/wiki/ISO_8601). So the string you have printed as an example represents:
41 days and 16 hours

While it is an ISO standard, Excel seems to not have a built in way of decoding it. This would have to be done e.g. by some VBA script or possibly some fancy string manipulation formula.

**Comment by DanyHubGit** [comment]
> Both attributes are in the [ISO 8601 duration format](https://en.wikipedia.org/wiki/ISO_8601). So the string you have printed as an example represents:
> 41 days and 16 hours
> 
> While it is an ISO standard, Excel seems to not have a built in way of decoding it. This would have to be done e.g. by some VBA script or possibly some fancy string manipulation formula.

Thanks for explanation.
Sorry but, how have you decoded **P41DT16H** to **41 days and 16 hours**?

**Comment by ulferts** [comment]
Copied from the wiki page:

> P is the duration designator (for period) placed at the start of the duration representation.
>   * Y is the year designator that follows the value for the number of years.
>   * M is the month designator that follows the value for the number of months.
>   * W is the week designator that follows the value for the number of weeks.
>   * D is the day designator that follows the value for the number of days.
>
> T is the time designator that precedes the time components of the representation.
>   * H is the hour designator that follows the value for the number of hours.
>   * M is the minute designator that follows the value for the number of minutes.
>   * S is the second designator that follows the value for the number of seconds.
> 
> For example, "P3Y6M4DT12H30M5S" represents a duration of "three years, six months, four days, twelve hours, thirty minutes, and five seconds".

So the Period (P) part is P41D and the Time (T) part is T16H. The period part contains only one number followed by a D for days. That translates to 41 days. The time part contains only one number followed by an H for hours which translates to 16 hours.

**Comment by DanyHubGit** [comment]
> Copied from the wiki page:
> 
> > P is the duration designator (for period) placed at the start of the duration representation.
> > 
> > * Y is the year designator that follows the value for the number of years.
> > * M is the month designator that follows the value for the number of months.
> > * W is the week designator that follows the value for the number of weeks.
> > * D is the day designator that follows the value for the number of days.
> > 
> > T is the time designator that precedes the time components of the representation.
> > 
> > * H is the hour designator that follows the value for the number of hours.
> > * M is the minute designator that follows the value for the number of minutes.
> > * S is the second designator that follows the value for the number of seconds.
> > 
> > For example, "P3Y6M4DT12H30M5S" represents a duration of "three years, six months, four days, twelve hours, thirty minutes, and five seconds".
> 
> So the Period (P) part is P41D and the Time (T) part is T16H. The period part contains only one number followed by a D for days. That translates to 41 days. The time part contains only one number followed by an H for hours which translates to 16 hours.

@ulferts  
Thank you so much!
