### ISSUE TITLE
Default columns

### ISSUE THREAD

**Issue by lindenthal** [opf/OpenProjectExcel#8]
Hi @bpetraus,
A new user always needs to configure some attributes such as lock version, subject, ID. Is it possible to preset these attributes in the template sheet? So a new user does not need to figure out how to select these columns. Does this make sense for you?
Best
Niels

**Comment by bpetraus** [comment]
Hi @lindenthal ,
done. Thank you for the hint.
Can you please try?
Best
Bernd

**Comment by sunishnet** [comment]
In fact all the fields can be put in the default template

**Comment by bpetraus** [comment]
Of course, you can create your own template anytime. But it is specific to the users language. So, I'm not able to provide a default template for every language, you know? 

How it is done now: If the sheet is empty the mandatory columns will be filled in the useres language.

**Comment by lindenthal** [comment]
Hi @bpetraus,

works like a charme! :-)

Thanks a lot,
Niels
